### ISSUE TITLE
UI element for "title" data

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/TimelineJS3#53] opened 2015-01-15 19:42 UTC
re: https://github.com/NUKnightLab/TimelineJS3/issues/36

There will be no marker in TimeNav for the 'title' slide, since there will be no dates associated with the title.  I'm assuming we will need some sort of UI element for the title slide.  The proposal was to have something on the left side of the TimeNav.

**Comment by zachwise** [comment] 2015-03-25 19:43
Seeing how this is currently the way the old timeline works, let's move this to the "future" milestone.

**Comment by thejordan** [comment] 2015-05-12 19:53
duplicate of #57

**Closed by thejordan** 2015-05-12 19:53 UTC
Labels: CSS
