### ISSUE TITLE
When events are re-laid out into multiple rows, groups don't adjust correctly.

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#331] opened 2016-01-19 18:28 UTC
A user sent a test example demonstrating that when one zooms in to a timeline in a way that causes events to be reassigned to new rows, the 'group' rows don't correctly adjust.

**Comment by scott2b** [comment] 2016-10-19 14:47
@JoeGermuska do you have this example? I don't know how to replicate this otherwise

**Comment by PaulCoetser** [comment] 2016-10-26 07:00
I do experience the same problem with the zoom factor.  easy way to recreate it is as follows:

Group1 - that contains an event that is today
Group 2 - that contains an event that is today + 1 day, 
Group 3 - that contains an event that is today + 2 days
Group 4 - that contains an event that is today + 3 days

Group 1 - contains an event that also belongs to Group1 but the event is today + 4 days

Have your browser window on a fairly small resolution, +- 1200 x 800

the default zoom factor is on 2.  Zoom in to 1x, and then Zoom in to 0.5

you should see this behavior.

My limited fix is to limit the zoom factors....  it will still appear but not so often.

 scale_factor: 2,  
zoom_sequence: [1, 2, 5, 9, 15],   //[0.5, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

**Comment by scott2b** [comment] 2016-11-03 17:13
@PaulCoetser I am unable to reproduce the problem in the manner you describe. Do you have a spreadsheet already made that I could copy for reproducing this issue? Could you also tell me what browser you are seeing this in.

Thanks!

**Comment by PaulCoetser** [comment] 2016-11-16 03:14
@scott2b, 
I have attached a html and json file where I was able to recreate it with these 2 files.

I get this behavior in Chrome, Opera, Edge, IE and Firefox.
Please let me know it you need anything else.

and sorry for the slow reply.  

![beforezoom](https://cloud.githubusercontent.com/assets/5609389/20333462/a8e5388a-abed-11e6-8e82-cdf0bc783ae6.PNG)
![zoom2times](https://cloud.githubusercontent.com/assets/5609389/20333463/a8e9977c-abed-11e6-8a19-7ef9b7e6a4d5.PNG)
[group_sample.zip](https://github.com/NUKnightLab/TimelineJS3/files/593679/group_sample.zip)

**Comment by PaulCoetser** [comment] 2016-11-16 03:41
In the group_sample.html within the zip file you can replace the <body> </body> block with this block below to simplify the alternatives.

<body>
     <div id="timeline"></div>
      <script src="../js/timeline.js"></script>
    <script>
      var timeline = new TL.Timeline('timeline', 'group_sample.json', {
      });
      window.onresize = function(event) {
      	timeline.updateDisplay();
      }
    </script>
  </body>

**Comment by PaulCoetser** [comment] 2016-11-16 04:56
ElMacBgl's solution on issue #378 worked for me as well.

**Comment by scott2b** [comment] 2017-11-27 16:00
I have tried the provided zipped example. I am still unable to reproduce the problem. Other than needing to fix the json to properly apply Group 4 to the final slide, I do not see any problems

@PaulCoetser can you verify if this is still an issue?

**Comment by scott2b** [comment] 2017-11-27 17:39
Never mind. I was able to replicate finally. It seems that this is fixed simply by clearing out the _groups array when _createGroups is called. As-is, this array is growing indefinitely on various redraw events

**Comment by scott2b** [comment] 2019-01-11 20:37
Fixed by #562

**Closed by scott2b** 2019-01-11 20:37 UTC
Labels: Bug, Time axis layout: markers and groups
