### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by guilhermejcgois** [NUKnightLab/TimelineJS3#589] opened 2018-08-31 21:42 UTC
Hi, I'm having issues with my jenkins environment when installing this package from this repo, that is the message:

```
~\Jenkins\workspace\job>npm install 
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: github:NUKnightLab/TimelineJS3.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

I have tried figured out what is the problem but no success yet.
I have found this [package](https://www.npmjs.com/package/timelinejs3) on NPM, is an official one?

I really need that solved, if I can do something to help u help me, please, let me now! 😄 

Cheers, 🍻

**Comment by guilhermejcgois** [comment] 2019-01-08 19:06
Some update about that? if the referred package is official, seems to be out dated with this repository... Something that can I help?

**Comment by JoeGermuska** [comment] 2020-07-09 16:14
duplicate of #308

**Closed by JoeGermuska** 2020-07-09 16:14 UTC
