### ISSUE TITLE
Timeline slider doesn't seem to slide on mouse drag

### ISSUE THREAD

**Issue by TheMicronaut** [NUKnightLab/TimelineJS3#457] opened 2017-01-15 17:22 UTC
When hovering the mouse over the timeline slider, the mouse pointer changes from arrow to cross. However, when clicking the mouse button to drag the timeline towards left or right, there is no interaction. 
Tested on chrome.

**Comment by thehandsomepanther** [comment] 2017-01-17 22:45
Hi @TheMicronaut can you provide some more information? What version of Chrome are you using? What timeline have you tested with? I just tried it on the Women in Computing timeline on the from page of timeline.knightlab.com and it seems to work fine for me on both Safari 10.0.2 and Chrome 55.

**Comment by TheMicronaut** [comment] 2017-01-17 23:20
hi @thehandsomepanther,
I tested the exact same timeline as you did in timeline.knightlab.com page. I used latest chrome  55.0.2883.87 and still slider doesn't seem to work. Same for the Vivaldi browser (chromium based). However, I just tested it with Firefox and works like charm. Perhaps is a javascript issue with chromium?

**Comment by TheMicronaut** [comment] 2017-01-20 19:39
some more hints:
the problem seems to be that the position of 'tl-timenav-slider' is not updated on mouse drag. Using Debug tools on chrome, I found that while enabling the 'Toggle Device Toolbar' button, the problem is not reproducible.

**Comment by VinelaP** [comment] 2017-02-03 20:04
Looks like either mouse OR touch sliding is supported but not both. If the device/browser is detected as touch capable, then only touch sliding would work. I would expect both touch and mouse navigation to work on a touch device.

**Comment by TheMicronaut** [comment] 2017-02-03 20:48
indeed @VinelaP, this seems to be a valid conclusion. My system is touch capable (slider works on touch screen), yet I use it via mouse/non-touch-monitor (slider doesn't respond).

**Comment by JoeGermuska** [comment] 2017-02-06 15:30
Timeline's handling of touch predates wide availability of touchscreen devices which also used mouse/pointer-type devices. We know that this is something to revisit, but have not scheduled the work yet.

**Comment by manndave** [comment] 2017-04-09 20:20
Any update or workaround for this?

**Comment by scott2b** [comment] 2017-04-11 00:08
this is a duplicate of #181. Please follow that issue in lieu of this one

**Closed by scott2b** 2017-04-11 00:08 UTC
Labels: Bug
