### ISSUE TITLE
Current date slide display option

### ISSUE THREAD

**Issue by kevinsdooapp** [NUKnightLab/TimelineJS3#199] opened 2015-08-13 13:04 UTC
Hi!

Great works! TimelineJS is really useful but It could be nice to have a display option which position the slide available to the current time.

Thank you

Kevin

**Comment by JoeGermuska** [comment] 2015-08-13 14:01
Duplicate of #75

**Closed by JoeGermuska** 2015-08-13 14:01 UTC

**Comment by keunes** [comment] 2015-10-07 15:42
Hi @kevinsdooapp
If you have the opportunity, it would be great if you could explain your use case in the discussion of Feature Request #75. This helps the developers to get an understanding of what we want and may contribute to the feature being added sooner :)
