### ISSUE TITLE
makeGoogleMapsEmbedURL issue in Strict Mode

### ISSUE THREAD

**Issue by daveygroup** [NUKnightLab/TimelineJS3#698] opened 2021-04-19 06:38 UTC
In `makeGoogleMapsEmbedURL` there is a problem when in strict mode.
```javascript
if (i = !0, "place" == a) var o = t.match(l.place)[3] + "," + t.match(l.place)[4];
else {
    o = r.center;
    delete r.center
} (r = {}).location = o, streetview_params = e.split(",");
```

**Comment by daveygroup** [comment] 2021-04-20 01:47
#### Use Case

1. Create a new project in Visual Studio
2. Extend Visual Studio by installing [BundlerMinifier](https://github.com/madskristensen/BundlerMinifier)
3. Put a beautified version of timeline.js in the project.
4. Right-click  timeline.js and choose to minify so that timeline.min.js gets created

#### Result
Silently fails to create minified version.

Goto Error window and the following error will be visible:
`Error (Bundler & Minifier) Strict-mode does not allow assignment to undefined variables: streetview_params`

There are actually 2 errors. 

1.  The first one is removed by changing `o = r.center` to `var o = r.center`.
2.  The second is at this code `(r = {}).location = o, streetview_params = e.split(",");`

I resolved by commenting out that line (because I do not use map media and that code will never be reached)

**Comment by JoeGermuska** [comment] 2021-04-20 14:57
Thanks, this is thorough, and will help us troubleshoot.

The problem is that the lines at the heart of the problem are not in the TimelineJS code base; they're produced by Webpack in the bundling process. (By `terser`, I think, but a lot of Webpack is mysterious to me.)

But at least what you've provided would give us a way to see if a change in the original code addressed the issue.

Anyway, here's the original code: 
https://github.com/NUKnightLab/TimelineJS3/blob/ced25c4c2bf323f102170dd8b86661340921844b/src/js/media/types/GoogleMap.js#L56-L61

I wonder if it would work better if `center` were initialized earlier, outside of that snaky if/else chain. When I have time to install BundlerMinifier i will give it a try, or, if you're so inclined, you could check out this repo and try it yourself!

**Comment by daveygroup** [comment] 2021-04-21 01:12
I'm just a self-taught web developer, and maybe lack a deeper understanding of how everything fits together. I read code more like "lambda" blocks, processing it in piece meals. When you speak "web pack" and "builders", my "inclined" makes space for "not knowledgeable enough." Close the issue... I thought it was something simple as a one-liner, which I just couldn't figure out...
...the matter of fact is that this is a pre-runtime issue trying to minify the code using a specific development environment and "minifier", and that the code is still functional.

**Comment by JoeGermuska** [comment] 2021-04-21 16:38
Ah, well, Webpack is probably more or less like Bundler & Minifier, except that it isn't integrated into a code editor.  So part of what's weird is that you're setting up to minify code which has already been minified.

If you are able, things might work better if you can install packages from NPM -- [Timeline is available here](https://www.npmjs.com/package/@knight-lab/timelinejs).

Otherwise, I think we'll take your suggestion to close this issue, esp. because Bundler & Minifier seems to be for Visual Studio (which we don't use) not Visual Studio Code (which we do).

**Closed by JoeGermuska** 2021-04-21 16:38 UTC
Labels: needs verification
