### ISSUE TITLE
Support for different calendar types?

### ISSUE THREAD

**Issue by mohsaied** [NUKnightLab/TimelineJS3#628] opened 2019-12-16 23:15 UTC
I was hoping to use timelineJS with a 'hijri' lunar calendar. I think it should be easy to add support for that but not sure where to start. All it needs is different month names and different 'BCE' abbreviations.

**Comment by JoeGermuska** [comment] 2019-12-17 16:10
@mohsaied Thanks for your interest.  This is effectively a duplicate of #83 so I'm going to close this and respond further to you there.

**Closed by JoeGermuska** 2019-12-17 16:10 UTC
