### ISSUE TITLE
Error Loading Assets Upon Landing

### ISSUE THREAD

**Issue by johnman025** [NUKnightLab/TimelineJS3#632] opened 2020-03-10 20:00 UTC
![Screen Shot 2020-03-10 at 12 55 57 PM](https://user-images.githubusercontent.com/62034623/76353906-c79d9600-62ce-11ea-944f-0f603a202df7.png)

Timeline assets would load in an error on the front end:

https://www.milkenarchive.org/articles/view/milken-archive-of-jewish-music-1990present/

I've attempted to reproduce this bug by simply refreshing the browser and it seem to happen at random. Most of the time, however, the timeline does work properly. The bug shown here does go away upon page refresh but of course, we want a consistent display. 

Any help would be much appreciated, thank you!

**Comment by JoeGermuska** [comment] 2020-03-10 20:13
This issue typically arises when a timeline is loaded into a container which is not visible at load time. In this case, the timeline gets incorrect information about the available width and height to lay itself out, and then, when the parent is made visible, the iframe containing the timeline doesn't get its own resize-message, which prevents it from adjusting its layout to the new screen geometry.

I notice that in your page, the timeline is included in a div with the CSS class `collapse` which suggests it may be the case with your page as well.  If it is, our first recommendation would be "don't do that," although that's typically easier said than done.  But you may need to look at instrumenting your page to either not load the timeline until the "collapse" state is changed ("uncollapsed" or "expanded") or similar strategies.

I also note, when viewing source for your page, that there appear to be some mismatched HTML tags, which could contribute to issues in the browser properly rendering the page. Anything you can do to ensure that all of your HTML is valid would help eliminate those as possible factors in the bad display.

But more generally, this seems unlikely to be a true bug in TimelineJS as much as interplay between our tool and details of your site implementation. As such, I'm closing this ticket. We can continue to discuss here, if you like, or you can submit a support request at https://knightlab.zendesk.com/hc/en-us/requests/new

**Closed by JoeGermuska** 2020-03-10 20:13 UTC

**Comment by johnman025** [comment] 2020-03-10 20:27
Thank you Joe, I'll get in touch with our dev on this matter and clean out the tags on the page itself.

**Comment by KINKCreative** [comment] 2020-03-10 21:04
@JoeGermuska the collapse class is a ZURB Foundation class which only removes paddings on a row, it is not an interactivity element like in bootstrap that would expand/collapse. My guess is that it has to do with the width="100%" since that's not HTML5 compliant. We're trying a 1200 (px) fixed width and capping the width to 100% with inline CSS. Will keep you posted if that changes anything.

**Comment by JoeGermuska** [comment] 2020-03-10 21:47
Thank you -- especially if you can find any consistent way to reproduce the issue. 

Even though this is something we've occasionally seen, I have not been able to see it on your page, even trying in a few browsers and clearing caches, etc.

**Comment by FSaldanha** [comment] 2020-08-04 17:33
I had exactly the same issue and could fix it by styling an empty div with correct dimensions, then appending the timeline's iframe to that div on page load via JS.
