### ISSUE TITLE
Knight Lab map URL does not show expected map in embed.

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#98] opened 2015-06-04 22:24 UTC
This map URL:
https://www.google.com/maps/place/1845+Sheridan+Rd,+Northwestern+University,+Evanston+Campus,+Evanston,+IL+60208/@42.0507251,-87.6742358,17z/data=!3m1!4b1!4m2!3m1!1s0x880fd0746c9b0007:0x8bb1a9034220562f

shows this in a timeline:

![image](https://cloud.githubusercontent.com/assets/46313/7995730/85edbc32-0ade-11e5-899d-7e45d7dcf994.png)

**Comment by hbillings** [comment] 2015-06-10 15:18
For posterity, in case this comes up later: This issue seems to be caused by the presence of multiple place names ("Northwestern University, Evanston Campus") in the address. "Northwestern University" alone works fine. The fix for this is to add the `center` parameter to our query, so that even if Google Maps can't find the place, the map is at least centered over the right location.

**Closed by hbillings** 2015-06-10 15:18 UTC
Labels: Bug, Plugin or Integration with Service
