### ISSUE TITLE
Group resize issue

### ISSUE THREAD

**Issue by roypardi** [NUKnightLab/TimelineJS3#348] opened 2016-02-28 18:40 UTC
Hi – great lib!

Firefox 44.0.2  - OSX 10.11.2  

I've been exploring some of the settings to customize a timeline through the JSON and am seeing some oddness with the `group` option. Perhaps I am defining the `group` incorrectly? A JSON snippet defining one event is below, along with screenshots of the glitches.

```
{
        "media": {
            "url": "./assets/brian_consult_play_button.jpg",
            "thumbnail": "./assets/brian_consult_play_button.jpg"
        },
        "start_date": {
            "year": "1986"
        },
        "text": {
            "headline": "The Life of Brian",
            "text": "<p>Graduates from Reed College</p>"
        },
        "background": {
            "color": "#3b92a1"
        },
        "group":"Brian"
    }
```

The timeline after initial load:  
<img width="321" alt="screen shot 2016-02-28 at 1 25 13 pm" src="https://cloud.githubusercontent.com/assets/9053196/13381050/74a93978-de1f-11e5-8477-34b396eb08af.png">

After clicking "zoom+" a few times: the bottom group is off screen:  
<img width="307" alt="screen shot 2016-02-28 at 1 25 34 pm" src="https://cloud.githubusercontent.com/assets/9053196/13381051/84f18790-de1f-11e5-9ed5-d26388cdc2f6.png">

After clicking "zoom-" a few times: top group is duplicated:  
<img width="312" alt="screen shot 2016-02-28 at 1 26 07 pm" src="https://cloud.githubusercontent.com/assets/9053196/13381055/89fcb156-de1f-11e5-91f4-8323aca42669.png">

**Comment by scott2b** [comment] 2017-04-10 23:39
duplicate of #378

**Closed by scott2b** 2017-04-10 23:39 UTC
Labels: Bug
