### ISSUE TITLE
gregorian to jalali

### ISSUE THREAD

**Issue by miladmodaresi** [NUKnightLab/TimelineJS3#630] opened 2020-02-19 08:44 UTC
How can I use the Persian (Jalali) calendar in your timeline?

**Comment by JoeGermuska** [comment] 2020-07-10 16:11
This is a duplicate of #83 

We are open to guidance on how to adapt JavaScript dates to Jalali or other calendars, but it's something about which we are, unfortunately, ignorant, and have not had the resources to investigate.

**Closed by JoeGermuska** 2020-07-10 16:11 UTC
